// Code generated by Kitex v0.16.3. DO NOT EDIT.

package auth

import (
	"context"

	"github.com/cloudwego/prutal"
)

type AuthContext struct {
	UserId   int64    `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Username string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Roles    []string `protobuf:"bytes,3,rep,name=roles" json:"roles,omitempty"`
}

func (x *AuthContext) Reset() { *x = AuthContext{} }

func (x *AuthContext) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AuthContext) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AuthContext) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthContext) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ValidateSessionRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id" json:"session_id,omitempty"`
}

func (x *ValidateSessionRequest) Reset() { *x = ValidateSessionRequest{} }

func (x *ValidateSessionRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ValidateSessionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ValidateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CheckPermissionRequest struct {
	UserId int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Code   string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (x *CheckPermissionRequest) Reset() { *x = CheckPermissionRequest{} }

func (x *CheckPermissionRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CheckPermissionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckPermissionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPermissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CheckPermissionResponse struct {
	Allowed bool `protobuf:"varint,1,opt,name=allowed" json:"allowed,omitempty"`
}

func (x *CheckPermissionResponse) Reset() { *x = CheckPermissionResponse{} }

func (x *CheckPermissionResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CheckPermissionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type AuthService interface {
	ValidateSession(ctx context.Context, req *ValidateSessionRequest) (res *AuthContext, err error)
	CheckPermission(ctx context.Context, req *CheckPermissionRequest) (res *CheckPermissionResponse, err error)
}
