// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: idl/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_idl_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_idl_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AdminUser) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminUser) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AdminLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	mi := &file_idl_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	User          *AdminUser             `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResponse) Reset() {
	*x = AdminLoginResponse{}
	mi := &file_idl_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResponse) ProtoMessage() {}

func (x *AdminLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResponse.ProtoReflect.Descriptor instead.
func (*AdminLoginResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AdminLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AdminLoginResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type GetCurrentAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentAdminRequest) Reset() {
	*x = GetCurrentAdminRequest{}
	mi := &file_idl_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentAdminRequest) ProtoMessage() {}

func (x *GetCurrentAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentAdminRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentAdminRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_proto_rawDescGZIP(), []int{3}
}

type GetCurrentAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentAdminResponse) Reset() {
	*x = GetCurrentAdminResponse{}
	mi := &file_idl_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentAdminResponse) ProtoMessage() {}

func (x *GetCurrentAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentAdminResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentAdminResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrentAdminResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshAdminTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAdminTokenRequest) Reset() {
	*x = RefreshAdminTokenRequest{}
	mi := &file_idl_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAdminTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminTokenRequest) ProtoMessage() {}

func (x *RefreshAdminTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshAdminTokenRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshAdminTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshAdminTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAdminTokenResponse) Reset() {
	*x = RefreshAdminTokenResponse{}
	mi := &file_idl_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAdminTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminTokenResponse) ProtoMessage() {}

func (x *RefreshAdminTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshAdminTokenResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshAdminTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshAdminTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_idl_auth_proto protoreflect.FileDescriptor

const file_idl_auth_proto_rawDesc = "" +
	"\n" +
	"\x0eidl/auth.proto\x12\x04auth\"\x91\x01\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"K\n" +
	"\x11AdminLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"n\n" +
	"\x12AdminLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12#\n" +
	"\x04user\x18\x03 \x01(\v2\x0f.auth.AdminUserR\x04user\"\x18\n" +
	"\x16GetCurrentAdminRequest\">\n" +
	"\x17GetCurrentAdminResponse\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.auth.AdminUserR\x04user\"0\n" +
	"\x18RefreshAdminTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"P\n" +
	"\x19RefreshAdminTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt2\xf4\x01\n" +
	"\vAuthService\x12?\n" +
	"\n" +
	"AdminLogin\x12\x17.auth.AdminLoginRequest\x1a\x18.auth.AdminLoginResponse\x12N\n" +
	"\x0fGetCurrentAdmin\x12\x1c.auth.GetCurrentAdminRequest\x1a\x1d.auth.GetCurrentAdminResponse\x12T\n" +
	"\x11RefreshAdminToken\x12\x1e.auth.RefreshAdminTokenRequest\x1a\x1f.auth.RefreshAdminTokenResponseB6Z4github.com/Loe1210/personal-site/biz/model/auth;authb\x06proto3"

var (
	file_idl_auth_proto_rawDescOnce sync.Once
	file_idl_auth_proto_rawDescData []byte
)

func file_idl_auth_proto_rawDescGZIP() []byte {
	file_idl_auth_proto_rawDescOnce.Do(func() {
		file_idl_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_auth_proto_rawDesc), len(file_idl_auth_proto_rawDesc)))
	})
	return file_idl_auth_proto_rawDescData
}

var file_idl_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_idl_auth_proto_goTypes = []any{
	(*AdminUser)(nil),                 // 0: auth.AdminUser
	(*AdminLoginRequest)(nil),         // 1: auth.AdminLoginRequest
	(*AdminLoginResponse)(nil),        // 2: auth.AdminLoginResponse
	(*GetCurrentAdminRequest)(nil),    // 3: auth.GetCurrentAdminRequest
	(*GetCurrentAdminResponse)(nil),   // 4: auth.GetCurrentAdminResponse
	(*RefreshAdminTokenRequest)(nil),  // 5: auth.RefreshAdminTokenRequest
	(*RefreshAdminTokenResponse)(nil), // 6: auth.RefreshAdminTokenResponse
}
var file_idl_auth_proto_depIdxs = []int32{
	0, // 0: auth.AdminLoginResponse.user:type_name -> auth.AdminUser
	0, // 1: auth.GetCurrentAdminResponse.user:type_name -> auth.AdminUser
	1, // 2: auth.AuthService.AdminLogin:input_type -> auth.AdminLoginRequest
	3, // 3: auth.AuthService.GetCurrentAdmin:input_type -> auth.GetCurrentAdminRequest
	5, // 4: auth.AuthService.RefreshAdminToken:input_type -> auth.RefreshAdminTokenRequest
	2, // 5: auth.AuthService.AdminLogin:output_type -> auth.AdminLoginResponse
	4, // 6: auth.AuthService.GetCurrentAdmin:output_type -> auth.GetCurrentAdminResponse
	6, // 7: auth.AuthService.RefreshAdminToken:output_type -> auth.RefreshAdminTokenResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_idl_auth_proto_init() }
func file_idl_auth_proto_init() {
	if File_idl_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_auth_proto_rawDesc), len(file_idl_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_auth_proto_goTypes,
		DependencyIndexes: file_idl_auth_proto_depIdxs,
		MessageInfos:      file_idl_auth_proto_msgTypes,
	}.Build()
	File_idl_auth_proto = out.File
	file_idl_auth_proto_goTypes = nil
	file_idl_auth_proto_depIdxs = nil
}
