// Code generated by Kitex v0.16.3. DO NOT EDIT.

package authservice

import (
	"context"
	"errors"
	auth "github.com/Loe1210/personal-site/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ValidateSession": kitex.NewMethodInfo(
		validateSessionHandler,
		newValidateSessionArgs,
		newValidateSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CheckPermission": kitex.NewMethodInfo(
		checkPermissionHandler,
		newCheckPermissionArgs,
		newCheckPermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	authServiceServiceInfo                = NewServiceInfo()
	authServiceServiceInfoForClient       = NewServiceInfoForClient()
	authServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*auth.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "auth",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func validateSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.ValidateSessionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).ValidateSession(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ValidateSessionArgs:
		success, err := handler.(auth.AuthService).ValidateSession(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ValidateSessionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newValidateSessionArgs() interface{} {
	return &ValidateSessionArgs{}
}

func newValidateSessionResult() interface{} {
	return &ValidateSessionResult{}
}

type ValidateSessionArgs struct {
	Req *auth.ValidateSessionRequest
}

func (p *ValidateSessionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ValidateSessionArgs) Unmarshal(in []byte) error {
	msg := new(auth.ValidateSessionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ValidateSessionArgs_Req_DEFAULT *auth.ValidateSessionRequest

func (p *ValidateSessionArgs) GetReq() *auth.ValidateSessionRequest {
	if !p.IsSetReq() {
		return ValidateSessionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ValidateSessionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ValidateSessionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ValidateSessionResult struct {
	Success *auth.AuthContext
}

var ValidateSessionResult_Success_DEFAULT *auth.AuthContext

func (p *ValidateSessionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ValidateSessionResult) Unmarshal(in []byte) error {
	msg := new(auth.AuthContext)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ValidateSessionResult) GetSuccess() *auth.AuthContext {
	if !p.IsSetSuccess() {
		return ValidateSessionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ValidateSessionResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.AuthContext)
}

func (p *ValidateSessionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ValidateSessionResult) GetResult() interface{} {
	return p.Success
}

func checkPermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(auth.CheckPermissionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(auth.AuthService).CheckPermission(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckPermissionArgs:
		success, err := handler.(auth.AuthService).CheckPermission(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckPermissionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckPermissionArgs() interface{} {
	return &CheckPermissionArgs{}
}

func newCheckPermissionResult() interface{} {
	return &CheckPermissionResult{}
}

type CheckPermissionArgs struct {
	Req *auth.CheckPermissionRequest
}

func (p *CheckPermissionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckPermissionArgs) Unmarshal(in []byte) error {
	msg := new(auth.CheckPermissionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckPermissionArgs_Req_DEFAULT *auth.CheckPermissionRequest

func (p *CheckPermissionArgs) GetReq() *auth.CheckPermissionRequest {
	if !p.IsSetReq() {
		return CheckPermissionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckPermissionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckPermissionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckPermissionResult struct {
	Success *auth.CheckPermissionResponse
}

var CheckPermissionResult_Success_DEFAULT *auth.CheckPermissionResponse

func (p *CheckPermissionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckPermissionResult) Unmarshal(in []byte) error {
	msg := new(auth.CheckPermissionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckPermissionResult) GetSuccess() *auth.CheckPermissionResponse {
	if !p.IsSetSuccess() {
		return CheckPermissionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckPermissionResult) SetSuccess(x interface{}) {
	p.Success = x.(*auth.CheckPermissionResponse)
}

func (p *CheckPermissionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckPermissionResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ValidateSession(ctx context.Context, Req *auth.ValidateSessionRequest) (r *auth.AuthContext, err error) {
	var _args ValidateSessionArgs
	_args.Req = Req
	var _result ValidateSessionResult
	if err = p.c.Call(ctx, "ValidateSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckPermission(ctx context.Context, Req *auth.CheckPermissionRequest) (r *auth.CheckPermissionResponse, err error) {
	var _args CheckPermissionArgs
	_args.Req = Req
	var _result CheckPermissionResult
	if err = p.c.Call(ctx, "CheckPermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
