// Code generated by Kitex v0.16.3. DO NOT EDIT.

package content

import (
	"context"
	"github.com/Loe1210/personal-site/kitex_gen/base"

	"github.com/cloudwego/prutal"
)

type Tag struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
}

func (x *Tag) Reset() { *x = Tag{} }

func (x *Tag) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Tag) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Category struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Slug        string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (x *Category) Reset() { *x = Category{} }

func (x *Category) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Category) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Article struct {
	Id          int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Slug        string  `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	Summary     string  `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	ContentMd   string  `protobuf:"bytes,5,opt,name=content_md" json:"content_md,omitempty"`
	ContentHtml string  `protobuf:"bytes,6,opt,name=content_html" json:"content_html,omitempty"`
	CoverImage  string  `protobuf:"bytes,7,opt,name=cover_image" json:"cover_image,omitempty"`
	CategoryId  int64   `protobuf:"varint,8,opt,name=category_id" json:"category_id,omitempty"`
	TagIds      []int64 `protobuf:"varint,9,rep,packed,name=tag_ids" json:"tag_ids,omitempty"`
	Status      string  `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
	Tags        []*Tag  `protobuf:"bytes,11,rep,name=tags" json:"tags,omitempty"`
}

func (x *Article) Reset() { *x = Article{} }

func (x *Article) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Article) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *Article) GetContentHtml() string {
	if x != nil {
		return x.ContentHtml
	}
	return ""
}

func (x *Article) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Article) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Article) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *Article) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Article) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetArticleByIDRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetArticleByIDRequest) Reset() { *x = GetArticleByIDRequest{} }

func (x *GetArticleByIDRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetArticleByIDRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetArticleByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPublicArticlesRequest struct {
	Page     int64  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=page_size" json:"page_size,omitempty"`
	Keyword  string `protobuf:"bytes,3,opt,name=keyword" json:"keyword,omitempty"`
}

func (x *ListPublicArticlesRequest) Reset() { *x = ListPublicArticlesRequest{} }

func (x *ListPublicArticlesRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListPublicArticlesRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListPublicArticlesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPublicArticlesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPublicArticlesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListArticlesResponse struct {
	List     []*Article     `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Total    int64          `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	BaseResp *base.BaseResp `protobuf:"bytes,100,opt,name=base_resp" json:"base_resp,omitempty"`
}

func (x *ListArticlesResponse) Reset() { *x = ListArticlesResponse{} }

func (x *ListArticlesResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListArticlesResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListArticlesResponse) GetList() []*Article {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListArticlesResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GetArticleResponse struct {
	Article  *Article       `protobuf:"bytes,1,opt,name=article" json:"article,omitempty"`
	BaseResp *base.BaseResp `protobuf:"bytes,100,opt,name=base_resp" json:"base_resp,omitempty"`
}

func (x *GetArticleResponse) Reset() { *x = GetArticleResponse{} }

func (x *GetArticleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetArticleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *GetArticleResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type CreateArticleRequest struct {
	Article *Article `protobuf:"bytes,1,opt,name=article" json:"article,omitempty"`
}

func (x *CreateArticleRequest) Reset() { *x = CreateArticleRequest{} }

func (x *CreateArticleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateArticleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleRequest struct {
	Article *Article `protobuf:"bytes,1,opt,name=article" json:"article,omitempty"`
}

func (x *UpdateArticleRequest) Reset() { *x = UpdateArticleRequest{} }

func (x *UpdateArticleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateArticleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type DeleteArticleRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *DeleteArticleRequest) Reset() { *x = DeleteArticleRequest{} }

func (x *DeleteArticleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteArticleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArticleResponse struct {
	Success  bool           `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	BaseResp *base.BaseResp `protobuf:"bytes,100,opt,name=base_resp" json:"base_resp,omitempty"`
}

func (x *DeleteArticleResponse) Reset() { *x = DeleteArticleResponse{} }

func (x *DeleteArticleResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DeleteArticleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteArticleResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ContentService interface {
	GetArticleByID(ctx context.Context, req *GetArticleByIDRequest) (res *GetArticleResponse, err error)
	ListPublicArticles(ctx context.Context, req *ListPublicArticlesRequest) (res *ListArticlesResponse, err error)
	CreateArticle(ctx context.Context, req *CreateArticleRequest) (res *GetArticleResponse, err error)
	UpdateArticle(ctx context.Context, req *UpdateArticleRequest) (res *GetArticleResponse, err error)
	DeleteArticle(ctx context.Context, req *DeleteArticleRequest) (res *DeleteArticleResponse, err error)
}
