server:
  host: ""
  port: "9002"
rpc:
  port: "9102"

mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: ""
  dbname: "media_db"
  charset: "utf8mb4"

upload:
  root_dir: "static/uploads/images"
  public_base_path: "/static/uploads/images"
  tmp_root_dir: "static/uploads/tmp"
  max_image_size_mb: 5

site:
  title: "Media Service"
  base_url: "http://localhost:9002"
