// Code generated by Kitex v0.16.3. DO NOT EDIT.

package contentservice

import (
	"context"
	content "github.com/Loe1210/personal-site/kitex_gen/content"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetArticleByID(ctx context.Context, Req *content.GetArticleByIDRequest, callOptions ...callopt.Option) (r *content.GetArticleResponse, err error)
	ListPublicArticles(ctx context.Context, Req *content.ListPublicArticlesRequest, callOptions ...callopt.Option) (r *content.ListArticlesResponse, err error)
	CreateArticle(ctx context.Context, Req *content.CreateArticleRequest, callOptions ...callopt.Option) (r *content.GetArticleResponse, err error)
	UpdateArticle(ctx context.Context, Req *content.UpdateArticleRequest, callOptions ...callopt.Option) (r *content.GetArticleResponse, err error)
	DeleteArticle(ctx context.Context, Req *content.DeleteArticleRequest, callOptions ...callopt.Option) (r *content.DeleteArticleResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kContentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kContentServiceClient struct {
	*kClient
}

func (p *kContentServiceClient) GetArticleByID(ctx context.Context, Req *content.GetArticleByIDRequest, callOptions ...callopt.Option) (r *content.GetArticleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetArticleByID(ctx, Req)
}

func (p *kContentServiceClient) ListPublicArticles(ctx context.Context, Req *content.ListPublicArticlesRequest, callOptions ...callopt.Option) (r *content.ListArticlesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPublicArticles(ctx, Req)
}

func (p *kContentServiceClient) CreateArticle(ctx context.Context, Req *content.CreateArticleRequest, callOptions ...callopt.Option) (r *content.GetArticleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateArticle(ctx, Req)
}

func (p *kContentServiceClient) UpdateArticle(ctx context.Context, Req *content.UpdateArticleRequest, callOptions ...callopt.Option) (r *content.GetArticleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateArticle(ctx, Req)
}

func (p *kContentServiceClient) DeleteArticle(ctx context.Context, Req *content.DeleteArticleRequest, callOptions ...callopt.Option) (r *content.DeleteArticleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteArticle(ctx, Req)
}
