// Code generated by Kitex v0.16.3. DO NOT EDIT.

package contentservice

import (
	"context"
	"errors"
	content "github.com/Loe1210/personal-site/kitex_gen/content"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetArticleByID": kitex.NewMethodInfo(
		getArticleByIDHandler,
		newGetArticleByIDArgs,
		newGetArticleByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListPublicArticles": kitex.NewMethodInfo(
		listPublicArticlesHandler,
		newListPublicArticlesArgs,
		newListPublicArticlesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateArticle": kitex.NewMethodInfo(
		createArticleHandler,
		newCreateArticleArgs,
		newCreateArticleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateArticle": kitex.NewMethodInfo(
		updateArticleHandler,
		newUpdateArticleArgs,
		newUpdateArticleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteArticle": kitex.NewMethodInfo(
		deleteArticleHandler,
		newDeleteArticleArgs,
		newDeleteArticleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	contentServiceServiceInfo                = NewServiceInfo()
	contentServiceServiceInfoForClient       = NewServiceInfoForClient()
	contentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return contentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return contentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return contentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ContentService"
	handlerType := (*content.ContentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "content",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func getArticleByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetArticleByIDRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetArticleByID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetArticleByIDArgs:
		success, err := handler.(content.ContentService).GetArticleByID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetArticleByIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetArticleByIDArgs() interface{} {
	return &GetArticleByIDArgs{}
}

func newGetArticleByIDResult() interface{} {
	return &GetArticleByIDResult{}
}

type GetArticleByIDArgs struct {
	Req *content.GetArticleByIDRequest
}

func (p *GetArticleByIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetArticleByIDArgs) Unmarshal(in []byte) error {
	msg := new(content.GetArticleByIDRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetArticleByIDArgs_Req_DEFAULT *content.GetArticleByIDRequest

func (p *GetArticleByIDArgs) GetReq() *content.GetArticleByIDRequest {
	if !p.IsSetReq() {
		return GetArticleByIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetArticleByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetArticleByIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetArticleByIDResult struct {
	Success *content.GetArticleResponse
}

var GetArticleByIDResult_Success_DEFAULT *content.GetArticleResponse

func (p *GetArticleByIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetArticleByIDResult) Unmarshal(in []byte) error {
	msg := new(content.GetArticleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetArticleByIDResult) GetSuccess() *content.GetArticleResponse {
	if !p.IsSetSuccess() {
		return GetArticleByIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetArticleByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetArticleResponse)
}

func (p *GetArticleByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetArticleByIDResult) GetResult() interface{} {
	return p.Success
}

func listPublicArticlesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.ListPublicArticlesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).ListPublicArticles(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListPublicArticlesArgs:
		success, err := handler.(content.ContentService).ListPublicArticles(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListPublicArticlesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListPublicArticlesArgs() interface{} {
	return &ListPublicArticlesArgs{}
}

func newListPublicArticlesResult() interface{} {
	return &ListPublicArticlesResult{}
}

type ListPublicArticlesArgs struct {
	Req *content.ListPublicArticlesRequest
}

func (p *ListPublicArticlesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListPublicArticlesArgs) Unmarshal(in []byte) error {
	msg := new(content.ListPublicArticlesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListPublicArticlesArgs_Req_DEFAULT *content.ListPublicArticlesRequest

func (p *ListPublicArticlesArgs) GetReq() *content.ListPublicArticlesRequest {
	if !p.IsSetReq() {
		return ListPublicArticlesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListPublicArticlesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListPublicArticlesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListPublicArticlesResult struct {
	Success *content.ListArticlesResponse
}

var ListPublicArticlesResult_Success_DEFAULT *content.ListArticlesResponse

func (p *ListPublicArticlesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListPublicArticlesResult) Unmarshal(in []byte) error {
	msg := new(content.ListArticlesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListPublicArticlesResult) GetSuccess() *content.ListArticlesResponse {
	if !p.IsSetSuccess() {
		return ListPublicArticlesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListPublicArticlesResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.ListArticlesResponse)
}

func (p *ListPublicArticlesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListPublicArticlesResult) GetResult() interface{} {
	return p.Success
}

func createArticleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.CreateArticleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).CreateArticle(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateArticleArgs:
		success, err := handler.(content.ContentService).CreateArticle(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateArticleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateArticleArgs() interface{} {
	return &CreateArticleArgs{}
}

func newCreateArticleResult() interface{} {
	return &CreateArticleResult{}
}

type CreateArticleArgs struct {
	Req *content.CreateArticleRequest
}

func (p *CreateArticleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateArticleArgs) Unmarshal(in []byte) error {
	msg := new(content.CreateArticleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateArticleArgs_Req_DEFAULT *content.CreateArticleRequest

func (p *CreateArticleArgs) GetReq() *content.CreateArticleRequest {
	if !p.IsSetReq() {
		return CreateArticleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateArticleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateArticleResult struct {
	Success *content.GetArticleResponse
}

var CreateArticleResult_Success_DEFAULT *content.GetArticleResponse

func (p *CreateArticleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateArticleResult) Unmarshal(in []byte) error {
	msg := new(content.GetArticleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateArticleResult) GetSuccess() *content.GetArticleResponse {
	if !p.IsSetSuccess() {
		return CreateArticleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetArticleResponse)
}

func (p *CreateArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateArticleResult) GetResult() interface{} {
	return p.Success
}

func updateArticleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.UpdateArticleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).UpdateArticle(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateArticleArgs:
		success, err := handler.(content.ContentService).UpdateArticle(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateArticleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateArticleArgs() interface{} {
	return &UpdateArticleArgs{}
}

func newUpdateArticleResult() interface{} {
	return &UpdateArticleResult{}
}

type UpdateArticleArgs struct {
	Req *content.UpdateArticleRequest
}

func (p *UpdateArticleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateArticleArgs) Unmarshal(in []byte) error {
	msg := new(content.UpdateArticleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateArticleArgs_Req_DEFAULT *content.UpdateArticleRequest

func (p *UpdateArticleArgs) GetReq() *content.UpdateArticleRequest {
	if !p.IsSetReq() {
		return UpdateArticleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateArticleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateArticleResult struct {
	Success *content.GetArticleResponse
}

var UpdateArticleResult_Success_DEFAULT *content.GetArticleResponse

func (p *UpdateArticleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateArticleResult) Unmarshal(in []byte) error {
	msg := new(content.GetArticleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateArticleResult) GetSuccess() *content.GetArticleResponse {
	if !p.IsSetSuccess() {
		return UpdateArticleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetArticleResponse)
}

func (p *UpdateArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateArticleResult) GetResult() interface{} {
	return p.Success
}

func deleteArticleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.DeleteArticleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).DeleteArticle(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteArticleArgs:
		success, err := handler.(content.ContentService).DeleteArticle(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteArticleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteArticleArgs() interface{} {
	return &DeleteArticleArgs{}
}

func newDeleteArticleResult() interface{} {
	return &DeleteArticleResult{}
}

type DeleteArticleArgs struct {
	Req *content.DeleteArticleRequest
}

func (p *DeleteArticleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteArticleArgs) Unmarshal(in []byte) error {
	msg := new(content.DeleteArticleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteArticleArgs_Req_DEFAULT *content.DeleteArticleRequest

func (p *DeleteArticleArgs) GetReq() *content.DeleteArticleRequest {
	if !p.IsSetReq() {
		return DeleteArticleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteArticleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteArticleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteArticleResult struct {
	Success *content.DeleteArticleResponse
}

var DeleteArticleResult_Success_DEFAULT *content.DeleteArticleResponse

func (p *DeleteArticleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteArticleResult) Unmarshal(in []byte) error {
	msg := new(content.DeleteArticleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteArticleResult) GetSuccess() *content.DeleteArticleResponse {
	if !p.IsSetSuccess() {
		return DeleteArticleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteArticleResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.DeleteArticleResponse)
}

func (p *DeleteArticleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteArticleResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetArticleByID(ctx context.Context, Req *content.GetArticleByIDRequest) (r *content.GetArticleResponse, err error) {
	var _args GetArticleByIDArgs
	_args.Req = Req
	var _result GetArticleByIDResult
	if err = p.c.Call(ctx, "GetArticleByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPublicArticles(ctx context.Context, Req *content.ListPublicArticlesRequest) (r *content.ListArticlesResponse, err error) {
	var _args ListPublicArticlesArgs
	_args.Req = Req
	var _result ListPublicArticlesResult
	if err = p.c.Call(ctx, "ListPublicArticles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateArticle(ctx context.Context, Req *content.CreateArticleRequest) (r *content.GetArticleResponse, err error) {
	var _args CreateArticleArgs
	_args.Req = Req
	var _result CreateArticleResult
	if err = p.c.Call(ctx, "CreateArticle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateArticle(ctx context.Context, Req *content.UpdateArticleRequest) (r *content.GetArticleResponse, err error) {
	var _args UpdateArticleArgs
	_args.Req = Req
	var _result UpdateArticleResult
	if err = p.c.Call(ctx, "UpdateArticle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteArticle(ctx context.Context, Req *content.DeleteArticleRequest) (r *content.DeleteArticleResponse, err error) {
	var _args DeleteArticleArgs
	_args.Req = Req
	var _result DeleteArticleResult
	if err = p.c.Call(ctx, "DeleteArticle", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
