// Code generated by Kitex v0.16.3. DO NOT EDIT.

package base

import (
	"strconv"

	"github.com/cloudwego/prutal"
)

type ErrorCode int32

const (
	ErrorCode_ERROR_NONE                      ErrorCode = 0
	ErrorCode_ERROR_INVALID_ARGUMENT          ErrorCode = 20010001
	ErrorCode_ERROR_INTERNAL                  ErrorCode = 20010002
	ErrorCode_ERROR_AUTH_LOGIN_REQUIRED       ErrorCode = 20020001
	ErrorCode_ERROR_AUTH_SESSION_EXPIRED      ErrorCode = 20020002
	ErrorCode_ERROR_AUTH_PERMISSION_DENIED    ErrorCode = 20020003
	ErrorCode_ERROR_AUTH_UPSTREAM_FAILED      ErrorCode = 20020004
	ErrorCode_ERROR_CONTENT_ARTICLE_NOT_FOUND ErrorCode = 20030001
)

// Enum value maps for ErrorCode.
var ErrorCode_name = map[int32]string{
	0:        "ERROR_NONE",
	20010001: "ERROR_INVALID_ARGUMENT",
	20010002: "ERROR_INTERNAL",
	20020001: "ERROR_AUTH_LOGIN_REQUIRED",
	20020002: "ERROR_AUTH_SESSION_EXPIRED",
	20020003: "ERROR_AUTH_PERMISSION_DENIED",
	20020004: "ERROR_AUTH_UPSTREAM_FAILED",
	20030001: "ERROR_CONTENT_ARTICLE_NOT_FOUND",
}

var ErrorCode_value = map[string]int32{
	"ERROR_NONE":                      0,
	"ERROR_INVALID_ARGUMENT":          20010001,
	"ERROR_INTERNAL":                  20010002,
	"ERROR_AUTH_LOGIN_REQUIRED":       20020001,
	"ERROR_AUTH_SESSION_EXPIRED":      20020002,
	"ERROR_AUTH_PERMISSION_DENIED":    20020003,
	"ERROR_AUTH_UPSTREAM_FAILED":      20020004,
	"ERROR_CONTENT_ARTICLE_NOT_FOUND": 20030001,
}

func (x ErrorCode) String() string {
	s, ok := ErrorCode_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type BaseResp struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (x *BaseResp) Reset() { *x = BaseResp{} }

func (x *BaseResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BaseResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}
