// Code generated by Kitex v0.16.3. DO NOT EDIT.

package media

import (
	"context"

	"github.com/cloudwego/prutal"
)

type FileRecord struct {
	Id           int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	OriginalName string `protobuf:"bytes,2,opt,name=original_name" json:"original_name,omitempty"`
	Url          string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Path         string `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	ContentType  string `protobuf:"bytes,5,opt,name=content_type" json:"content_type,omitempty"`
	Size         int64  `protobuf:"varint,6,opt,name=size" json:"size,omitempty"`
	BizType      string `protobuf:"bytes,7,opt,name=biz_type" json:"biz_type,omitempty"`
	CreatedAt    string `protobuf:"bytes,8,opt,name=created_at" json:"created_at,omitempty"`
}

func (x *FileRecord) Reset() { *x = FileRecord{} }

func (x *FileRecord) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FileRecord) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FileRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileRecord) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *FileRecord) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRecord) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileRecord) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileRecord) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *FileRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetFileRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetFileRequest) Reset() { *x = GetFileRequest{} }

func (x *GetFileRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetFileRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFileResponse struct {
	File *FileRecord `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
}

func (x *GetFileResponse) Reset() { *x = GetFileResponse{} }

func (x *GetFileResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetFileResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetFileResponse) GetFile() *FileRecord {
	if x != nil {
		return x.File
	}
	return nil
}

type MediaService interface {
	GetFile(ctx context.Context, req *GetFileRequest) (res *GetFileResponse, err error)
}
