// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: idl/article.proto

package article

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	ContentMd     string                 `protobuf:"bytes,5,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	ContentHtml   string                 `protobuf:"bytes,6,opt,name=content_html,json=contentHtml,proto3" json:"content_html,omitempty"`
	CoverImage    string                 `protobuf:"bytes,7,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	CategoryId    int64                  `protobuf:"varint,8,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagIds        []int64                `protobuf:"varint,9,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,13,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_idl_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *Article) GetContentHtml() string {
	if x != nil {
		return x.ContentHtml
	}
	return ""
}

func (x *Article) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Article) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Article) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *Article) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Article) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Article) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Article) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	ContentMd     string                 `protobuf:"bytes,4,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	CategoryId    int64                  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagIds        []int64                `protobuf:"varint,7,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_idl_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateArticleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateArticleRequest) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *CreateArticleRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *CreateArticleRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateArticleRequest) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *CreateArticleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_idl_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *CreateArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	ContentMd     string                 `protobuf:"bytes,5,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	CoverImage    string                 `protobuf:"bytes,6,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TagIds        []int64                `protobuf:"varint,8,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_idl_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateArticleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateArticleRequest) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *UpdateArticleRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *UpdateArticleRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateArticleRequest) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *UpdateArticleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResponse) Reset() {
	*x = UpdateArticleResponse{}
	mi := &file_idl_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResponse) ProtoMessage() {}

func (x *UpdateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResponse.ProtoReflect.Descriptor instead.
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *UpdateArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_idl_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_idl_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetArticleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIDRequest) Reset() {
	*x = GetArticleByIDRequest{}
	mi := &file_idl_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIDRequest) ProtoMessage() {}

func (x *GetArticleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIDRequest.ProtoReflect.Descriptor instead.
func (*GetArticleByIDRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleBySlugRequest) Reset() {
	*x = GetArticleBySlugRequest{}
	mi := &file_idl_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleBySlugRequest) ProtoMessage() {}

func (x *GetArticleBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetArticleBySlugRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_idl_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{9}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Keyword       string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_idl_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{10}
}

func (x *ListArticlesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArticlesRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListArticlesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListArticlesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListArticlesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListAdminArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminArticlesRequest) Reset() {
	*x = ListAdminArticlesRequest{}
	mi := &file_idl_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminArticlesRequest) ProtoMessage() {}

func (x *ListAdminArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListAdminArticlesRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{11}
}

func (x *ListAdminArticlesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdminArticlesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminArticlesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAdminArticlesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Article             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_idl_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{12}
}

func (x *ListArticlesResponse) GetList() []*Article {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListArticlesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListArticlesResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PublishArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleRequest) Reset() {
	*x = PublishArticleRequest{}
	mi := &file_idl_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleRequest) ProtoMessage() {}

func (x *PublishArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleRequest.ProtoReflect.Descriptor instead.
func (*PublishArticleRequest) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{13}
}

func (x *PublishArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishArticleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PublishArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArticleResponse) Reset() {
	*x = PublishArticleResponse{}
	mi := &file_idl_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArticleResponse) ProtoMessage() {}

func (x *PublishArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArticleResponse.ProtoReflect.Descriptor instead.
func (*PublishArticleResponse) Descriptor() ([]byte, []int) {
	return file_idl_article_proto_rawDescGZIP(), []int{14}
}

func (x *PublishArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *PublishArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_idl_article_proto protoreflect.FileDescriptor

const file_idl_article_proto_rawDesc = "" +
	"\n" +
	"\x11idl/article.proto\x12\aarticle\"\xf3\x02\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"content_md\x18\x05 \x01(\tR\tcontentMd\x12!\n" +
	"\fcontent_html\x18\x06 \x01(\tR\vcontentHtml\x12\x1f\n" +
	"\vcover_image\x18\a \x01(\tR\n" +
	"coverImage\x12\x1f\n" +
	"\vcategory_id\x18\b \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\atag_ids\x18\t \x03(\x03R\x06tagIds\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12!\n" +
	"\fpublished_at\x18\r \x01(\tR\vpublishedAt\"\xec\x01\n" +
	"\x14CreateArticleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"content_md\x18\x04 \x01(\tR\tcontentMd\x12\x1f\n" +
	"\vcover_image\x18\x05 \x01(\tR\n" +
	"coverImage\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\atag_ids\x18\a \x03(\x03R\x06tagIds\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"]\n" +
	"\x15CreateArticleResponse\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfc\x01\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"content_md\x18\x05 \x01(\tR\tcontentMd\x12\x1f\n" +
	"\vcover_image\x18\x06 \x01(\tR\n" +
	"coverImage\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\atag_ids\x18\b \x03(\x03R\x06tagIds\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"]\n" +
	"\x15UpdateArticleResponse\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x15DeleteArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\x15GetArticleByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"-\n" +
	"\x17GetArticleBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"@\n" +
	"\x12GetArticleResponse\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\"\xa6\x01\n" +
	"\x13ListArticlesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"}\n" +
	"\x18ListAdminArticlesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\"\x83\x01\n" +
	"\x14ListArticlesResponse\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.article.ArticleR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"?\n" +
	"\x15PublishArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"^\n" +
	"\x16PublishArticleResponse\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x99\x05\n" +
	"\x0eArticleService\x12N\n" +
	"\rCreateArticle\x12\x1d.article.CreateArticleRequest\x1a\x1e.article.CreateArticleResponse\x12N\n" +
	"\rUpdateArticle\x12\x1d.article.UpdateArticleRequest\x1a\x1e.article.UpdateArticleResponse\x12N\n" +
	"\rDeleteArticle\x12\x1d.article.DeleteArticleRequest\x1a\x1e.article.DeleteArticleResponse\x12M\n" +
	"\x0eGetArticleByID\x12\x1e.article.GetArticleByIDRequest\x1a\x1b.article.GetArticleResponse\x12Q\n" +
	"\x10GetArticleBySlug\x12 .article.GetArticleBySlugRequest\x1a\x1b.article.GetArticleResponse\x12K\n" +
	"\fListArticles\x12\x1c.article.ListArticlesRequest\x1a\x1d.article.ListArticlesResponse\x12U\n" +
	"\x11ListAdminArticles\x12!.article.ListAdminArticlesRequest\x1a\x1d.article.ListArticlesResponse\x12Q\n" +
	"\x0ePublishArticle\x12\x1e.article.PublishArticleRequest\x1a\x1f.article.PublishArticleResponseB<Z:github.com/Loe1210/personal-site/biz/model/article;articleb\x06proto3"

var (
	file_idl_article_proto_rawDescOnce sync.Once
	file_idl_article_proto_rawDescData []byte
)

func file_idl_article_proto_rawDescGZIP() []byte {
	file_idl_article_proto_rawDescOnce.Do(func() {
		file_idl_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_article_proto_rawDesc), len(file_idl_article_proto_rawDesc)))
	})
	return file_idl_article_proto_rawDescData
}

var file_idl_article_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_idl_article_proto_goTypes = []any{
	(*Article)(nil),                  // 0: article.Article
	(*CreateArticleRequest)(nil),     // 1: article.CreateArticleRequest
	(*CreateArticleResponse)(nil),    // 2: article.CreateArticleResponse
	(*UpdateArticleRequest)(nil),     // 3: article.UpdateArticleRequest
	(*UpdateArticleResponse)(nil),    // 4: article.UpdateArticleResponse
	(*DeleteArticleRequest)(nil),     // 5: article.DeleteArticleRequest
	(*DeleteArticleResponse)(nil),    // 6: article.DeleteArticleResponse
	(*GetArticleByIDRequest)(nil),    // 7: article.GetArticleByIDRequest
	(*GetArticleBySlugRequest)(nil),  // 8: article.GetArticleBySlugRequest
	(*GetArticleResponse)(nil),       // 9: article.GetArticleResponse
	(*ListArticlesRequest)(nil),      // 10: article.ListArticlesRequest
	(*ListAdminArticlesRequest)(nil), // 11: article.ListAdminArticlesRequest
	(*ListArticlesResponse)(nil),     // 12: article.ListArticlesResponse
	(*PublishArticleRequest)(nil),    // 13: article.PublishArticleRequest
	(*PublishArticleResponse)(nil),   // 14: article.PublishArticleResponse
}
var file_idl_article_proto_depIdxs = []int32{
	0,  // 0: article.CreateArticleResponse.article:type_name -> article.Article
	0,  // 1: article.UpdateArticleResponse.article:type_name -> article.Article
	0,  // 2: article.GetArticleResponse.article:type_name -> article.Article
	0,  // 3: article.ListArticlesResponse.list:type_name -> article.Article
	0,  // 4: article.PublishArticleResponse.article:type_name -> article.Article
	1,  // 5: article.ArticleService.CreateArticle:input_type -> article.CreateArticleRequest
	3,  // 6: article.ArticleService.UpdateArticle:input_type -> article.UpdateArticleRequest
	5,  // 7: article.ArticleService.DeleteArticle:input_type -> article.DeleteArticleRequest
	7,  // 8: article.ArticleService.GetArticleByID:input_type -> article.GetArticleByIDRequest
	8,  // 9: article.ArticleService.GetArticleBySlug:input_type -> article.GetArticleBySlugRequest
	10, // 10: article.ArticleService.ListArticles:input_type -> article.ListArticlesRequest
	11, // 11: article.ArticleService.ListAdminArticles:input_type -> article.ListAdminArticlesRequest
	13, // 12: article.ArticleService.PublishArticle:input_type -> article.PublishArticleRequest
	2,  // 13: article.ArticleService.CreateArticle:output_type -> article.CreateArticleResponse
	4,  // 14: article.ArticleService.UpdateArticle:output_type -> article.UpdateArticleResponse
	6,  // 15: article.ArticleService.DeleteArticle:output_type -> article.DeleteArticleResponse
	9,  // 16: article.ArticleService.GetArticleByID:output_type -> article.GetArticleResponse
	9,  // 17: article.ArticleService.GetArticleBySlug:output_type -> article.GetArticleResponse
	12, // 18: article.ArticleService.ListArticles:output_type -> article.ListArticlesResponse
	12, // 19: article.ArticleService.ListAdminArticles:output_type -> article.ListArticlesResponse
	14, // 20: article.ArticleService.PublishArticle:output_type -> article.PublishArticleResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_idl_article_proto_init() }
func file_idl_article_proto_init() {
	if File_idl_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_article_proto_rawDesc), len(file_idl_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_article_proto_goTypes,
		DependencyIndexes: file_idl_article_proto_depIdxs,
		MessageInfos:      file_idl_article_proto_msgTypes,
	}.Build()
	File_idl_article_proto = out.File
	file_idl_article_proto_goTypes = nil
	file_idl_article_proto_depIdxs = nil
}
