// Code generated by Kitex v0.16.3. DO NOT EDIT.

package mediaservice

import (
	"context"
	media "github.com/Loe1210/personal-site/kitex_gen/media"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetFile(ctx context.Context, Req *media.GetFileRequest, callOptions ...callopt.Option) (r *media.GetFileResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMediaServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMediaServiceClient struct {
	*kClient
}

func (p *kMediaServiceClient) GetFile(ctx context.Context, Req *media.GetFileRequest, callOptions ...callopt.Option) (r *media.GetFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFile(ctx, Req)
}
