// Code generated by Kitex v0.16.3. DO NOT EDIT.

package mediaservice

import (
	"context"
	"errors"
	media "github.com/Loe1210/personal-site/kitex_gen/media"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetFile": kitex.NewMethodInfo(
		getFileHandler,
		newGetFileArgs,
		newGetFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	mediaServiceServiceInfo                = NewServiceInfo()
	mediaServiceServiceInfoForClient       = NewServiceInfoForClient()
	mediaServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return mediaServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return mediaServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return mediaServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MediaService"
	handlerType := (*media.MediaService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "media",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func getFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(media.GetFileRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(media.MediaService).GetFile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetFileArgs:
		success, err := handler.(media.MediaService).GetFile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetFileArgs() interface{} {
	return &GetFileArgs{}
}

func newGetFileResult() interface{} {
	return &GetFileResult{}
}

type GetFileArgs struct {
	Req *media.GetFileRequest
}

func (p *GetFileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetFileArgs) Unmarshal(in []byte) error {
	msg := new(media.GetFileRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFileArgs_Req_DEFAULT *media.GetFileRequest

func (p *GetFileArgs) GetReq() *media.GetFileRequest {
	if !p.IsSetReq() {
		return GetFileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetFileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetFileResult struct {
	Success *media.GetFileResponse
}

var GetFileResult_Success_DEFAULT *media.GetFileResponse

func (p *GetFileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetFileResult) Unmarshal(in []byte) error {
	msg := new(media.GetFileResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFileResult) GetSuccess() *media.GetFileResponse {
	if !p.IsSetSuccess() {
		return GetFileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*media.GetFileResponse)
}

func (p *GetFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetFileResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetFile(ctx context.Context, Req *media.GetFileRequest) (r *media.GetFileResponse, err error) {
	var _args GetFileArgs
	_args.Req = Req
	var _result GetFileResult
	if err = p.c.Call(ctx, "GetFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
